config/routes.rb
Rails.application.routes.draw do
  
  root 'site#home' 
        
  devise_for :students
  get 'students/profile', to: 'students#profile'
  
  
  devise_for :teachers
  get 'teachers/profile', to: 'teachers#profile'
  
    
  post '/search_sport', to: 'site#search' 
 
  get '/teachers/index', to: 'teachers#index', as: 'teachers'

  get '/teachers/:id/confirmed', to: 'teachers#show_confirmed', as: 'confirmed_appointments'

  get '/teachers/:id/pending', to: 'teachers#show_pending', as: 'pending_appointments'

  # get '/appointments/:id/change', to:'appointments#change', as: 'appointment_change'

  #post '/teachers/:id', to: 'students#show'

  # post '/student_profile/:id', to: 'students#confirm'

  # get '/sport_appointment/:id', to: 'appointments#show'
  # post '/appointments/:teacher_id', to:'appointments#create'
  
  resources :sports
  resources :appointments
  
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  belongs_to :sport
end

app/models/sport.rb
class Sport < ApplicationRecord
	before_save { self.name = name.downcase }
	# before_save { self.id = Sport.where(name: self.name).first_or_create.id }
  has_many :appointments

  has_many :teachers
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :appointments
  has_many :teachers, through: :appointments
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
	
	has_many :appointments
	has_many :students, through: :appointments  

	belongs_to :sport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  # def after_sign_in_path_for(teacher)
  #   appointments_path
  # end
  def after_sign_in_path_for(student)
    if current_student != nil
      student_path current_student
    else
      pending_appointments_path(current_teacher)
    end
  end
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :sport_id])
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_teacher!, only: :index
  before_action :authenticate_student!, only: :create 
  
  def index
    @pending_appointments = Appointment.where(teacher_id: current_teacher.id, confirmation: false).order("created_at desc")
    @confirmed_appointments = Appointment.where(teacher_id: current_teacher.id, confirmation: true).order("created_at desc")
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    
  end

  def create
  	@teacher = Teacher.find(params[:teacher_id])
    @sport = Sport.find(params[:sport_id])
    @student = current_student
    appointment = @teacher.appointments.new(student_id: @student.id, sport_id: @sport.id)
  	appointment.save
    
    redirect_to sports_path
  end

  def edit
    @appointment_change = Appointment.find(params[:id])
    @appointment_change.update(:confirmation => true)
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def home
    @sports = Sport.all
	end

	def search
		sport_id = params['sport']
		sport = Sport.find_by(id: sport_id)
		if sport
			redirect_to sport_path(sport)
		else
			render plain: 'No sports found'
		end
	end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
	before_action :authenticate_student!, except: [:show]

	def index
		@sports = Sport.all
		@student = current_student
		@appointments = Appointment.where(student_id: @student.id, confirmation: false).order("created_at DESC")
		@confirmed_appointments = Appointment.where(student_id: @student.id, confirmation: true).order("created_at DESC")
	end

	def show
		@sport = Sport.find_by(id: params[:id])
		if current_student
			@student = current_student
		end
	end

	def create
		teacher.appointment.create(appointment_params)
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  before_action :authenticate_student!, except: [:new, :create]
  
  def show
    @pending_appointments = Appointment.where(student_id: current_student.id, confirmation: false).order("created_at desc")
    @confirmed_appointments = Appointment.where(student_id: current_student.id, confirmation: true).order("created_at desc")
  end

  def confirm
  	@appointment = Appointment.find_by(id: params[:id])
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!, except: [:new, :create]

  def index
    @teachers = Teacher.all
  end

  def show_pending
  	@teacher = Teacher.find_by(id: params[:id])
  	unless @teacher
  		render 'no_user'
  	 	return
  	end
    @appointments = Appointment.where(teacher_id: current_teacher.id).where(confirmation: false).order("created_at desc")
  end

  def show_confirmed
    @teacher = Teacher.find_by(id: params[:id])
    unless @teacher
      render 'no_user'
      return
    end
    @confirmed_appointments = Appointment.where(teacher_id: current_teacher.id).where(confirmation: true).order("created_at desc")
  end


  def teacher_params
    params.require(:teacher).permit(:name, :email, :description, :age, :sport_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#     	before_action :authenticate_user!

# 		def profile
#             @user = current_user
#             render 'users/profile'
#         end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/appointments/edit.html.erb
<h2>Enhorabuena, en breve tendrás tu primera clase. Disfrútala</h2>
<%= button_to "Vuelve a tu perfil", :back, method: :get %>

app/views/appointments/index.html.erb
<h1>Vamos que lo tenemos!!</h1>

app/views/appointments/new.html.erb
<h2>Create your appointment</h2>

<%= form_for(@appointment, url: '/appointments', html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :sport %></br>
    <%= f.text_field :sport, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :date %></br>
    <%= f.text_field :date, autofocus: true %>
  </div>


  <div class="actions">
    <%= f.submit "Create your new apointment" %>
  </div>
<% end %>

app/views/appointments/show.html.erb
<!-- <h4>Hola, <%= @appointment.teacher.name %></h4> 
<h3>Tienes una nueva peticion de clase, a continuacion puedes ver todos los detalles</h3>

<ul>	
	<li> Sport: <%= @appointment.sport.name %></li>
	<p> El nombre del estudiante es el siguiente</p>
	<li> Student: <%= @appointment.student.name %></li>
	<p> la fecha para tu clase es:</p>
	<li> Fecha: <%= @appointment.date %></li>
	<p> Confirma tu clase en el siguiente botón %></p>
	<%= button_to "Confirma tu clase!", "/student_profile/#{@appointment.id}" %>
		
</ul> -->


<div class='wrap'>
	<div class="element1">
		<!-- <div class = "button-search-sport">
			<%= form_tag search_sport_path, method: 'post' do %>
		    <%= select_tag :sport, options_for_select(Sport.all.map { |sport| [sport.name.capitalize, sport.id] }) %>
		    <%= submit_tag 'search'%>
		 	<% end %>
		</div> -->
		<h3>Estas son las clases que tienes pendientes, a continuacion puedes ver todos los detalles</h3>
		<div class="reservas-teacher" style="color:black;text-align:left;">
			<% if @appointments.present? %>
					<h4> Aún no se han confirmado las siguientes reservas:</h4>
					<% @appointments.each do |appointment| %>
						<ul>	
							<li> Sport: <%= appointment.sport.name.titleize %></li>
							<li> Student: <%= appointment.student.name.titleize %></li>
							<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
							<li> Student age: <%= appointment.student.age %></li> 
						</ul>
						
					<% end %>
			<% end %>
		</div>
	</div>

	<div class= "eleimage"> 
		<img style="width: 95%; height: 95%;" src="mickfanning.jpg"/>
	</div>
</div>​

<div id="bottom_botons"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greatlearn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <div id="top_botons">
    <div><img id="tp1" style="width: 50px; height: 55px;" src="logo.png"/></div>
  
    <div id="tp2">
      <% if student_signed_in? %>
        <p><%= link_to 'Sign out', destroy_student_session_path, method:'DELETE' %></p>
      <% else %> 
        <p>
          <%= link_to 'Sign_up as student', new_student_registration_path %> |
          <%= link_to 'Sign_in as student', new_student_session_path %>
        </p>
      <% end %>
    </div>
    
    <div id="tp3">
      <% if teacher_signed_in? %>
        <p><%= link_to 'Sign out', destroy_teacher_session_path, method:'DELETE' %></p>
      <% else %> 
        <p>
          <%= link_to 'Sign_up as teacher', new_teacher_registration_path %> |
          <%= link_to 'Sign_in as teacher', new_teacher_session_path %>
        </p>
      <% end %>
    </div>
  </div>
</header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/site/home.html.erb
<div class='wrap'>
	<div class="element1">
		<div class = "imagelhome">
		<img style="width: 98%; height: 98%;" src="rsz_climbing.jpg"/>
	    </div>
	    <h3 class ="phome"> Aprende con los mejores cada uno de estos deportes </h2>
		<div class = "button-search-sport">
			<%= form_tag search_sport_path, method: 'post' do %>
		    <%= select_tag :sport, options_for_select(Sport.all.map { |sport| [sport.name.capitalize, sport.id] }) %>
		    <%= submit_tag 'search'%>
		 	<% end %>
		</div>
	</div>
		
	<div class= "eleimage"> 
		<img style="width: 98%; height: 95%;" src="mickfanning.jpg"/>
	</div>
</div>​

<div id="bottom_botons">
<div id = "bottom">
  <img src="tenis.png" width="350" height="150"  class="left" />
  <img src="basket.png" width="350" height="150"  class="right" />
  <img src="padel.png" width="350" height="150" />
</div>



</div>
</div>

			
	
	

app/views/sports/index.html.erb
<div class='wrap'>
	<div class="element1">
		<!-- <div class = "button-search-sport">
			<%= form_tag search_sport_path, method: 'post' do %>
		    <%= select_tag :sport, options_for_select(Sport.all.map { |sport| [sport.name.capitalize, sport.id] }) %>
		    <%= submit_tag 'search'%>
		 	<% end %>
		</div> -->
		<div class="reservas" style="color:black;text-align:left;">
			<% if @appointments.present? %>
					<h4> Tienes estas reservas a la espera de ser confirmadas por el profesor:</h4>
					<% @appointments.each do |appointment| %>
						<ul>	
							<li> Sport: <%= appointment.sport.name.titleize %></li>
							<li> Teacher: <%= appointment.teacher.name.titleize %></li>
							<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
							<li> Teacher description: <%= appointment.teacher.description %></li> 
						</ul>
						
					<% end %>
			<% end %>
		</div>
	</div>

	<div class= "eleimage"> 
		<img style="width: 95%; height: 95%;" src="mickfanning.jpg"/>
	</div>
</div>​

<div id="bottom_botons"></div>

app/views/sports/show.html.erb
<% if @sport.teachers.present? %>
	<h1>Este es el listado de profesores de <%= @sport.name.titleize %></h1>
<% else %>
	<h1>Lo sentimos, actualmente no hay profesores de <%= @sport.name.titleize %> disponibles.</h1>
<% end %>

<% @sport.teachers.each do |teacher| %>
	<ul>
		<li>Teacher: <%= teacher.name %></li>
		<li>Descripcion del profesor: <%= teacher.description %></li>
		<% if @student %>
			<li><%= @student.name.titleize %></li> 
		<%end%>

	<%= button_to "Solicita ahora tu clase!", appointments_path(teacher_id: teacher.id, sport_id: @sport.id), method: :post %>
	</ul>
	<br><br>
<% end %>	

		

<%= button_to "Elige otro deporte", :back, method: :get %>

app/views/students/confirm.html.erb
<h4>Hola, <%= @appointment.teacher.name %></h4> 
<h3>Tienes tu clase confirmada con,  </h3>
<h2>La fecha es:</h2>
<ul>
			<li> Fecha: <%= @appointment.date %></li>
			<p> Confirma tu clase en el siguiente botón %></p>
			<%= button_to "Confirma tu clase!", "/student_profile/" %>
</ul>
<h3>Disfrutala!</h3>		

app/views/students/show.html.erb
<h2>Hola <%= current_student.name %>!</h2>
<p>
<strong>Email:</strong> <%= current_student.email %>
</p>
<h3> Selecciona el deporte que quieres aprender </h3>

	<div>
			<%= form_tag search_sport_path, method: 'post' do %>
		    <%= select_tag :sport, options_for_select(Sport.all.map { |sport| [sport.name.capitalize, sport.id] }) %>
		    <%= submit_tag 'search'%>
		 	<% end %>
	</div>
	</div>
		<% if @confirmed_appointments.present? %>
				<h3> Este es el listado de clases que tienes confirmadas </h3>
				<% @confirmed_appointments.each do |appointment| %>
					<ul>	
						<li> Sport: <%= appointment.sport.name.titleize %></li>
						<li> Teacher: <%= appointment.teacher.name.titleize %></li>
						<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
						<li> Teacher age: <%= appointment.teacher.age %></li> 
					</ul>
				<% end %>
		<% end %>
	</div>

<% if @pending_appointments.present? %>
		<h3> Tienes a la espera de confirmación las siguientes clases:</h3>
			<% @pending_appointments.each do |appointment| %>
				<ul>	
					<li> Sport: <%= appointment.sport.name.titleize %></li>
					<li> Teacher: <%= appointment.teacher.name.titleize %></li>
					<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
					<li> Description: <%= appointment.teacher.description %></li> 
					</ul>	
				<% end %>
				<%= button_to "Vuelve a la home!", root_path, method: :get %>
		<% end %>
	</div>

app/views/teachers/index.html.erb
<h4>Este es el indice de profesores</h4>
<p>Deberán aparecer todos los profesores</p>


<ul>
	<% @teachers.each do |teacher| %>

	    <br>           
		<li>Name: <%= teacher.name %></li> 
		<li>Description: <%= teacher.description %></li>
		<li>Deporte: <%= teacher.sport %></li>
		------------------------------------------------

	<% end %>
</ul>

app/views/teachers/no_user.html.erb
<h4>There´s no teacher found for your request</h4>

app/views/teachers/profile.html.erb
<h2><%= current_teacher.name %>!</h2>
<p>
<strong>Email:</strong> <%= current_teacher.email %>
</p>

app/views/teachers/show_confirmed.html.erb
<h1>Hola <%= @teacher.name %>, bienvenido a tu perfil</h1>
<p>Name: <%= @teacher.name %></p>
<p>El mail con el que apareces en la plataforma es: <%= @teacher.email %></p>

<br>
<h1>Este es el listado de clases que tienes confirmadas</h1>

	<% if @confirmed_appointments.present? %>
			<% @confirmed_appointments.each do |appointment| %>
				<ul>	
					<li> Sport: <%= appointment.sport.name.titleize %></li>
					<li> Student: <%= appointment.student.name.titleize %></li>
					<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
					<li> Student age: <%= appointment.student.age %></li> 
					</ul>
				<% end %>
		<% end %>
	</div>
	<%= button_to "Vuelve a tu perfil", :back, method: :get %>
</div>

app/views/teachers/show_pending.html.erb
<h1>Hola <%= @teacher.name %>, bienvenido a tu perfil</h1>
<p>El mail con el que apareces en la plataforma es: <%= @teacher.email %></p>
<h3>En el siguiente botón podrás ver el listado de clases que tienes confirmadas</h3>
<%= button_to "clases confirmadas!", confirmed_appointments_path(@teacher), method: :get %>
<h3>Este es el listado de clases que tienes pendientes</h3>

	<% if @appointments.present? %>
		<h4> Aún no se han confirmado las siguientes reservas:</h4>
			<% @appointments.each do |appointment| %>
				<ul>	
					<li> Sport: <%= appointment.sport.name.titleize %></li>
					<li> Student: <%= appointment.student.name.titleize %></li>
					<li> Fecha: <%= appointment.created_at.strftime("%d.%m.%y at %H:%M") %></li>
					<li> Student age: <%= appointment.student.age %></li> 
					</ul>
				<%= button_to "Confirma tu clase!", edit_appointment_path(appointment), method: :get %>	
				<% end %>
		<% end %>
	</div>
	<%= button_to "Vuelve a la home!", root_path, method: :get %>	
</div>